// FILE: types/index.ts (Final and Complete Version)

// First, import the types generated by Prisma
import type { Order as PrismaOrder, OrderItem as PrismaOrderItem } from '@prisma/client';

// Defines the shape of a single product
export interface Product {
  id: number;
  name: string;
  price: string;
  priceNumber: number;
  image: string;
  category: string;
  description?: string;
  ingredients?: string;
  storage?: string;
  available: boolean;
}

// Defines the shape of an item when it's in the shopping cart
export interface CartItem extends Product {
  quantity: number;
}

// This is our new, complete Order type that includes the "items" relationship.
// It combines the base Order type from Prisma with its related OrderItems.
export type OrderWithItems = PrismaOrder & {
  items: PrismaOrderItem[];
};